import * as THREE from './vendor/three.module.min.js';
import {CARDS} from './game-cards.js';
const $=id=>document.getElementById(id);
const stageNames={input:'◒',key:'✦',cards:'◇',printing:'▧',done:'✓'};
const state={stage:'input',growth:null,relation:null,answerId:null,selected:null,job:null,progress:0,rolling:false,generation:{status:'idle',imageUrl:null,progress:0}};
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(0,1.2,9);camera.lookAt(0,.2,0);
let renderer=null;
try{
  renderer=new THREE.WebGLRenderer({canvas:$('#scene'),alpha:true,antialias:true});
  renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));
}catch(error){
  // Some exhibition laptops/browser shells do not expose WebGL. Keep the
  // complete game state machine usable so hardware and interaction can still
  // be tested; the canvas remains a quiet visual placeholder in that case.
  document.body.dataset.webgl='unavailable';
}
scene.add(new THREE.HemisphereLight(0xffffff,0xe4d8e0,2));const keyLight=new THREE.PointLight(0xffa39c,5,14);keyLight.position.set(-3,4,4);scene.add(keyLight);const fill=new THREE.PointLight(0x86d7e8,4,15);fill.position.set(4,1,2);scene.add(fill);
const root=new THREE.Group();scene.add(root);const floor=new THREE.Mesh(new THREE.CircleGeometry(5.5,64),new THREE.MeshBasicMaterial({color:0xe8dedf,transparent:true,opacity:.34}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.55;root.add(floor);
function roundedBox(w,h,d,color,op=.85){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,transparent:op<1,opacity:op,roughness:.65,metalness:.05}));return m}
// Input plinth and two dice.
const plinth=roundedBox(3.8,.3,2.2,0xd6c3da,.65);plinth.position.set(-2.25,-1.35,.2);root.add(plinth);
const dice=[];const dieColors=[0xc89acb,0x7dbcc5];
function makeDie(x,color){const g=new THREE.Group();const mesh=roundedBox(.95,.95,.95,color,.95);g.add(mesh);const ring=new THREE.Mesh(new THREE.TorusGeometry(.58,.015,8,40),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.45}));ring.rotation.x=Math.PI/2;g.add(ring);g.position.set(x,-.55,.25);root.add(g);return g}
dice.push(makeDie(-2.85,dieColors[0]),makeDie(-1.65,dieColors[1]));
// The first touch is a visual seed deck now; keep the old die meshes as a
// reserved hardware layer without letting them compete with the cards.
plinth.visible=false; dice.forEach(die=>{die.visible=false});
// Printer body, gantry, bed and printed object (digital twin).
const printer=new THREE.Group();printer.position.set(1.85,-.35,.15);root.add(printer);const body=roundedBox(3.05,2.55,2.25,0xa995bd,.22);body.position.y=-.05;printer.add(body);const bed=roundedBox(2.3,.12,1.55,0xd3c5d7,.8);bed.position.set(0,-.92,.15);printer.add(bed);const gantry=roundedBox(.1,2.1,.1,0x765d80,.8);gantry.position.set(-1.05,.2,.15);printer.add(gantry);const rail=roundedBox(2.2,.09,.09,0x765d80,.8);rail.position.set(0,1.16,.15);printer.add(rail);const nozzle=roundedBox(.18,.3,.18,0xff9a88,.95);nozzle.position.set(-.6,.97,.15);printer.add(nozzle);const printObj=new THREE.Mesh(new THREE.IcosahedronGeometry(.72,2),new THREE.MeshStandardMaterial({color:0xe68ba0,roughness:.35,metalness:.18,transparent:true,opacity:.92}));printObj.position.set(0,-.75,.15);printObj.scale.setScalar(.05);printer.add(printObj);
// 12 card wall in 3D behind printer.
const wall=new THREE.Group();wall.position.set(1.1,1.15,-1.15);root.add(wall);const cardMeshes=[];
function cardTexture(card){const c=document.createElement('canvas');c.width=220;c.height=300;const x=c.getContext('2d');const bg=x.createLinearGradient(0,0,220,300);bg.addColorStop(0,'#20243a');bg.addColorStop(.48,'#090b14');bg.addColorStop(1,'#17152a');x.fillStyle=bg;x.fillRect(0,0,c.width,c.height);const glow=x.createRadialGradient(110,142,8,110,142,105);glow.addColorStop(0,`${card.color}cc`);glow.addColorStop(.35,`${card.color}55`);glow.addColorStop(1,'rgba(12,12,24,0)');x.fillStyle=glow;x.fillRect(12,12,196,276);x.strokeStyle='#b9aaf0';x.lineWidth=2;x.strokeRect(10,10,c.width-20,c.height-20);x.strokeStyle='rgba(255,255,255,.34)';x.lineWidth=1;x.strokeRect(17,17,c.width-34,c.height-34);x.fillStyle='#ded7ff';x.font='12px monospace';x.textAlign='left';x.fillText(card.id,24,34);x.textAlign='right';x.fillStyle='rgba(225,218,255,.65)';x.font='10px monospace';x.fillText('⌘',196,34);x.textAlign='center';x.fillStyle='#f1eaff';x.shadowColor=card.color;x.shadowBlur=18;x.font='56px Georgia';x.fillText(card.symbol,110,146);x.shadowBlur=0;x.fillStyle='#e7defb';x.font='bold 18px monospace';x.fillText(card.symbol,110,266);return new THREE.CanvasTexture(c)}
CARDS.forEach((card,i)=>{const m=new THREE.Mesh(new THREE.PlaneGeometry(.42,.58),new THREE.MeshBasicMaterial({map:cardTexture(card),transparent:true,opacity:.72}));m.position.set((i%6)*.48-1.2,Math.floor(i/6)*.7-.3,0);wall.add(m);cardMeshes.push(m)});
function resize(){const canvas=$('scene')||document.querySelector('canvas')||document.documentElement;const r=canvas.getBoundingClientRect();if(renderer)renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();root.scale.setScalar(Math.min(r.width,r.height)/760)}addEventListener('resize',resize);resize();
function setStage(s){state.stage=s;document.body.dataset.stage=s;$('stageLabel').textContent=stageNames[s]||s;document.querySelector('.left-panel').hidden=s!=='input';['keyPanel','cardsPanel','printPanel'].forEach(id=>$(id).hidden=true);if(s==='key')$('keyPanel').hidden=false;if(s==='cards')$('cardsPanel').hidden=false;if(s==='printing'||s==='done')$('printPanel').hidden=false}
const seedSymbols=CARDS.map(card=>card.symbol);
function renderSeedDeck(){
  const deck=$('seedDeck'); if(!deck)return; deck.innerHTML='';
  seedSymbols.forEach((symbol,index)=>{
    const b=document.createElement('button'); b.className='seed-card'; b.type='button';
    b.setAttribute('aria-label',`种子 ${index+1} ${symbol}`);
    b.innerHTML=`<span class="seed-card-inner"><span class="seed-card-face seed-card-front" aria-hidden="true">·</span><span class="seed-card-face seed-card-back" aria-hidden="true">${symbol}</span></span>`;
    b.onclick=()=>selectSeed(index,b); deck.append(b);
  });
}
function selectSeed(index,node){
  if(state.stage!=='input'||node.classList.contains('chosen'))return;
  node.classList.add('chosen');
  const value=index+1;
  if(state.growth===null){state.growth=value;$('seedOne').textContent=seedSymbols[index];$('status').textContent='第一颗种子已翻开。再选一颗，让它们相遇。';}
  else if(state.relation===null){state.relation=value;$('seedTwo').textContent=seedSymbols[index];$('status').textContent='两颗种子已相遇，可以生成钥匙。';$('lockInput').disabled=false;}
}
function createArtwork(card,key){const c=document.createElement('canvas');c.width=720;c.height=960;const x=c.getContext('2d');const bg=x.createLinearGradient(0,0,720,960);bg.addColorStop(0,'#20243a');bg.addColorStop(.5,'#080a12');bg.addColorStop(1,'#211936');x.fillStyle=bg;x.fillRect(0,0,720,960);const glow=x.createRadialGradient(360,420,18,360,420,320);glow.addColorStop(0,`${card.color}cc`);glow.addColorStop(.38,`${card.color}55`);glow.addColorStop(1,'rgba(8,8,18,0)');x.fillStyle=glow;x.fillRect(30,30,660,900);x.strokeStyle='#b9aaf0';x.lineWidth=6;x.strokeRect(28,28,664,904);x.strokeStyle='rgba(255,255,255,.38)';x.lineWidth=2;x.strokeRect(48,48,624,864);x.fillStyle='#ded7ff';x.font='28px monospace';x.fillText(card.id,72,102);x.textAlign='right';x.fillStyle='rgba(225,218,255,.7)';x.font='22px monospace';x.fillText(key.replaceAll(' · ','  '),648,102);x.textAlign='center';x.fillStyle='#f1eaff';x.shadowColor=card.color;x.shadowBlur=46;x.font='190px Georgia';x.fillText(card.symbol,360,500);x.shadowBlur=0;x.fillStyle='#e7defb';x.font='bold 42px monospace';x.fillText(card.symbol,360,810);return c.toDataURL('image/png')}
function preGenerateArtwork(card,key){const generation=state.generation;generation.status='generating';generation.progress=0;generation.imageUrl=createArtwork(card,key);$('generatedArt').src=generation.imageUrl;$('generatedArt').hidden=false;$('generationCopy').textContent='作品正在后台生成；找到卡片时会提前就绪。';const started=performance.now();function tick(now){generation.progress=Math.min(1,(now-started)/3200);$('generationProgress').style.width=`${Math.round(generation.progress*100)}%`;$('generationPercent').textContent=`${Math.round(generation.progress*100)}%`;if(generation.progress<1)requestAnimationFrame(tick);else{generation.status='ready';$('generationCopy').textContent='作品已生成，等待实体确认。'}}requestAnimationFrame(tick)}
function makeKey(){const n=(state.growth*7+state.relation*11)%12;state.answerId=n;state.job=`JOB-${Date.now().toString(36).slice(-5).toUpperCase()}`;$('jobText').textContent=state.job;const glyphs=['◒','⋔','◎','⊔','✳','◈','≈','⌑','∴','◇','△','∿'];const key=`${glyphs[state.growth-1]} · ${glyphs[state.relation+4]} · ${String(n+1).padStart(2,'0')}`;$('keyGlyph').textContent=key;$('targetHint').textContent=`${String(n+1).padStart(2,'0')} · ${CARDS[n].symbol}`;preGenerateArtwork(CARDS[n],key);$('status').textContent='钥匙已生成，作品已先行后台生成。带着线索去答案墙找卡片。';setStage('key')}
function renderCards(){const grid=$('cardGrid');grid.innerHTML='';CARDS.forEach((card,i)=>{const b=document.createElement('button');b.className='card';b.setAttribute('aria-label',`${card.id} ${card.name}`);b.innerHTML=`<span class="num">${card.id}</span><span class="symbol" aria-hidden="true">${card.symbol}</span><span class="name">${card.name}</span><span class="card-tag">NFC</span>`;b.onclick=()=>{state.selected=i;document.querySelectorAll('.card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('scanCard').disabled=false;$('manualCard').disabled=false;$('scanStatus').textContent=`已选择 ${card.id} · ${card.name}，等待实体确认。`;$('scanStatus').style.color='';cardMeshes.forEach((m,j)=>m.scale.setScalar(j===i?1.18:1));};grid.append(b)})}
function scan(method='nfc'){if(state.selected==null)return;if(state.selected!==state.answerId){$('scanStatus').textContent=`${method==='manual'?'电脑确认':'NFC'}：不匹配。钥匙还在寻找另一张卡。`;$('scanStatus').style.color='#b66b69';return}$('scanStatus').textContent=`${method==='manual'?'电脑确认':'NFC'}：匹配成功。预生成作品已锁定。`;$('scanStatus').style.color='#5d8a6b';showPrintReady()}
function showPrintReady(){setStage('printing');$('printTitle').textContent='▧';$('printTitle').setAttribute('aria-label','作品已就绪，等待打印');$('printCopy').textContent=`${state.job} · 预生成图已缓存，点击后发送到小米打印机。`;$('printArt').src=state.generation.imageUrl||createArtwork(CARDS[state.answerId],'cached');$('printArt').hidden=false;$('startPrintButton').hidden=false;$('restart').hidden=true;$('printProgress').style.width='0%';$('percentText').textContent='0%';$('layerText').textContent='◌'}
function startPrint(){setStage('printing');$('printTitle').textContent='⟶';$('printTitle').setAttribute('aria-label','正在发送到小米打印机');$('printCopy').textContent=`${state.job} · 使用已预生成作品，立即进入打印队列。`;$('printArt').src=state.generation.imageUrl||createArtwork(CARDS[state.answerId],'cached');$('printArt').hidden=false;$('startPrintButton').hidden=true;$('restart').hidden=true;state.progress=0;const started=performance.now();function step(now){state.progress=Math.min(1,(now-started)/8500);const p=state.progress;printObj.scale.setScalar(.05+p*.95);nozzle.position.x=-.9+p*1.7;$('printProgress').style.width=`${Math.round(p*100)}%`;$('percentText').textContent=`${Math.round(p*100)}%`;$('layerText').textContent=p<1?`${Math.max(1,Math.floor(p*38))} / 38`:'✓';if(p<1)requestAnimationFrame(step);else{setStage('done');$('printTitle').textContent='✓';$('printTitle').setAttribute('aria-label','作品完成，可以取出');$('printCopy').textContent=`${CARDS[state.answerId].id} · ${CARDS[state.answerId].name} 已发送至小米打印机。`;$('restart').hidden=false}}requestAnimationFrame(step)}
$('lockInput').onclick=makeKey;$('openCards').onclick=()=>{renderCards();setStage('cards')};$('scanCard').onclick=()=>scan('nfc');$('manualCard').onclick=()=>scan('manual');$('startPrintButton').onclick=startPrint;$('restart').onclick=()=>{location.reload()};renderSeedDeck();setStage('input');
function loop(now){printer.rotation.y=Math.sin(now*.0004)*.02;wall.rotation.y=Math.sin(now*.00025)*.025;printObj.rotation.y+=.006;if(renderer)renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
